name: test 

on: [push, pull_request, workflow_dispatch]

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: setup
        run: |
          cd google_image_searcher_v6
          python -m pip install --upgrade pip
          pip install -r requirements.txt

          mkdir upload
          wget -O upload/github.png "https://avatars.githubusercontent.com/u/9919?s=200&v=4"
          wget -O upload/crabby.png "https://rustacean.net/more-crabby-things/rustdocs.png"
          
      - name: 测试 Google 镜像
        run: |
          cd google_image_searcher_v6
          python main.py
          for dir in `find download -maxdepth 1 -mindepth 1 -type d`; do
              echo $dir && ls $dir
          done
          
      - name: 测试 Google 
        run: | 
          cd google_image_searcher_v6
          rm settings.json
          rm -rf download
          python main.py
          for dir in `find download -maxdepth 1 -mindepth 1 -type d`; do
              echo $dir && ls $dir
          done
